---
# tasks file for tower_saml

- name: outer block for default uri parameters
  block:

  - name: exclude configuration for vars only
    block:
    - name: generate certificate
      include_tasks:
        file: saml_cert.yml

    - name: configure SAML provider
      include_tasks:
        file: saml_config.yml
    when: not tower_saml_vars_only

  - name: get base configuration
    include_tasks:
      file: saml_get_config.yml

  module_defaults:
    uri:
      body_format: json
      return_content: yes
      url: "{{ tower_saml_endpoint}}"
      url_username: "{{ tower_saml_username }}"
      url_password: "{{ tower_saml_password }}"
      force_basic_auth: true
      validate_certs: false
