---
# tasks file for tower_saml

- block:

  - uri:
      method: GET
    register: tower_saml_config

  - debug: var=tower_saml_config

  module_defaults:
    uri:
      body_format: json
      return_content: yes
      url: "{{ tower_saml_endpoint}}"
      url_username: "{{ tower_saml_username }}"
      url_password: "{{ tower_saml_password }}"
      force_basic_auth: true
      validate_certs: false
