---
# tasks file for onelogin_user

- block:
  - name: Get apps
    uri:
      url: "{{ onelogin_base_url }}/{{ onelogin_app_api }}?name={{ onelogin_app_name }}"
      method: GET
    register: onelogin_apps

  - debug:
      var: onelogin_apps
      verbosity: 2

  - name: add application
    uri:
      url: "{{ onelogin_base_url }}/{{ onelogin_app_api }}"
      method: POST
      body: "{{ app_payload }}"
      status_code: [ 200, 201 ]
    when: not onelogin_apps.json
    register: onelogin_app_data

  - name: update application
    uri:
      url: "{{ onelogin_base_url }}/{{ onelogin_app_api }}/{{ onelogin_apps.json[0].id }}"
      method: PUT
      body: "{{ app_payload }}"
      status_code: [ 200, 201 ]
    when: onelogin_apps.json
    register: onelogin_app_data

  - name: set fact with application configuration needed outside
    set_fact:
      onelogin_app_certificate: "{{ _cert_value }}"
      onelogin_app_certificate_str: "{{ _cert_value_flat }}"
      # aka saml 2.0 endpoint
      onelogin_app_acs_url: "{{onelogin_app_data.json.sso.acs_url}}"
      onelogin_app_issuer_url: "{{onelogin_app_data.json.sso.issuer}}"
    vars:
      _cert_value: "{{ onelogin_app_data.json.sso.certificate.value }}"
      _cert_value_flat: "{{ _cert_value | replace('\n', '') | regex_replace('-*(BEGIN|END) CERTIFICATE-*','') }}"
    # COMMAND LINE FILTER
    #tr -d '\n' < saml_demo.crt | sed -e 's/-*BEGIN CERTIFICATE*-*//g' -e 's/-*END CERTIFICATE*-*//g'

  vars:
    app_payload:
      connector_id: "{{ onelogin_app_saml_connector_id }}"
      name: "{{ onelogin_app_name }}"
      description: "{{ onelogin_app_description }}"
      visible: true
      configuration:
        signature_algorithm: SHA-1
        audience: "{{ onelogin_app_saml_audience }}"
        consumer_url: "{{ onelogin_app_saml_consumer_url }}"
        logout_url: ''
        recipient: "{{ onelogin_app_saml_recipient_url }}"
        validator: .*
      role_ids:
        - "{{ onelogin_role_default_id }}"
      parameters:
        saml_username:
          id: 73732
          values:
          user_attribute_macros: ''
          label: Email (SAML NameID)
          provisioned_entitlements: false
          user_attribute_mappings: email
          attributes_transformations:
          default_values:
        PersonImmutableID:
          id: 73755
          values:
          user_attribute_macros:
          label: PersonImmutableID
          provisioned_entitlements: false
          user_attribute_mappings:
          attributes_transformations:
          default_values:
        User.LastName:
          id: 73741
          values:
          user_attribute_macros: ''
          label: Last Name (Attribute)
          provisioned_entitlements: false
          user_attribute_mappings: lastname
          attributes_transformations:
          default_values:
        User.email:
          id: 73739
          values:
          user_attribute_macros: ''
          label: E-mail (Attribute)
          provisioned_entitlements: false
          user_attribute_mappings: email
          attributes_transformations:
          default_values:
        memberOf:
          id: 73742
          values:
          user_attribute_macros: ''
          label: Member of (Groups) (Attribute)
          provisioned_entitlements: false
          user_attribute_mappings: member_of
          attributes_transformations:
          default_values:
        User.FirstName:
          id: 73740
          values:
          user_attribute_macros: ''
          label: First Name (Attribute)
          provisioned_entitlements: false
          user_attribute_mappings: firstname
          attributes_transformations:
          default_values:
        department:
          id: 305721
          values:
          user_attribute_macros: ''
          label: department
          provisioned_entitlements: false
          user_attribute_mappings: department
          attributes_transformations:
          default_values:
          include_in_saml_assertion: true

  module_defaults:
    uri:
      body_format: json
      return_content: yes
      headers:
        Authorization: "bearer {{ onelogin_token_access_token }}"
