---
# tasks file for onelogin_user

- block:
  - name: Get apps
    uri:
      url: "{{ onelogin_base_url }}/{{ onelogin_app_api }}?name={{ onelogin_app_name }}"
      method: GET
    register: onelogin_apps

  - debug:
      var: onelogin_apps
      verbosity: 2

  - name: add application
    uri:
      url: "{{ onelogin_base_url }}/{{ onelogin_app_api }}"
      method: POST
      body: "{{ app_payload }}"
      return_code: [ 200, 201 ]
    when: not onelogin_apps.json

  - name: update application
    uri:
      url: "{{ onelogin_base_url }}/{{ onelogin_app_api }}/{{ onelogin_apps.json[0].id }}"
      method: PUT
      body: "{{ app_payload }}"
      return_code: [ 200, 201 ]
    when: onelogin_apps.json
    register: onelongin_app_data

  - name: set fact with application configuration needed outside
    set_fact:
      onelogin_app_certificate: "{{ onelongin_app_data.json.sso.certificate.value }}"

  #tr -d '\n' < saml_demo.crt | sed -e 's/-*BEGIN CERTIFICATE*-*//g' -e 's/-*END CERTIFICATE*-*//g'

  vars:
    app_payload:
      connector_id: "{{ onelogin_app_saml_connector_id }}"
      name: "{{ onelogin_app_name }}"
      description: "{{ onelogin_app_description }}"
      visible: true
      configuration:
        signature_algorithm: SHA-1
        audience: towersaml
        consumer_url: https://petrivelli.synology.me/sso/complete/saml/
        logout_url: ''
        recipient: https://petrivelli.synology.me/sso/complete/saml/
        signature_algorithm: SHA-1
        validator: .*
  module_defaults:
    uri:
      body_format: json
      return_content: yes
      headers:
        Authorization: "bearer {{ onelogin_token_access_token }}"
