---
# defaults file for onelogin_app

onelogin_app_saml_test_connector_adv_id: 110016
onelogin_app_saml_test_connector_attr_id: 42657

onelogin_app_saml_connector_id: "{{onelogin_app_saml_test_connector_attr_id}}"


onelogin_app_api: api/2/apps
