allow_assumed_signin: false
auth_method: 2
configuration:
    audience: towersaml
    consumer_url: https://petrivelli.synology.me/sso/complete/saml/
    logout_url: ''
    recipient: https://petrivelli.synology.me/sso/complete/saml/
    relaystate: TEST
    signature_algorithm: SHA-1
    validator: .*
connector_id: 42657
created_at: '2019-05-13T01:09:40Z'
description: Ansible Tower
id: 932449
name: AnsibleTower
notes: ''
parameters:
    PersonImmutableID:
        attributes_transformations: null
        default_values: null
        id: 73755
        label: PersonImmutableID
        provisioned_entitlements: false
        user_attribute_macros: null
        user_attribute_mappings: none
        values: null
    User.FirstName:
        attributes_transformations: null
        default_values: null
        id: 73740
        label: First Name (Attribute)
        provisioned_entitlements: false
        user_attribute_macros: null
        user_attribute_mappings: firstname
        values: null
    User.LastName:
        attributes_transformations: null
        default_values: null
        id: 73741
        label: Last Name (Attribute)
        provisioned_entitlements: false
        user_attribute_macros: null
        user_attribute_mappings: lastname
        values: null
    User.email:
        attributes_transformations: null
        default_values: null
        id: 73739
        label: E-mail (Attribute)
        provisioned_entitlements: false
        user_attribute_macros: null
        user_attribute_mappings: email
        values: null
    memberOf:
        attributes_transformations: group_list
        default_values: null
        id: 73742
        label: Member of (Groups) (Attribute)
        provisioned_entitlements: false
        user_attribute_macros: groups
        user_attribute_mappings: member_of
        values: null
    saml_username:
        attributes_transformations: null
        default_values: null
        id: 73732
        label: Email (SAML NameID)
        provisioned_entitlements: false
        user_attribute_macros: null
        user_attribute_mappings: email
        values: null
    testfield1:
        attributes_transformations: null
        default_values: null
        id: 304540
        include_in_saml_assertion: true
        label: testfield1
        provisioned_entitlements: false
        user_attribute_macros: ''
        user_attribute_mappings: username
        values: null
policy_id: null
provisioning:
    enabled: false
role_ids:
- 263876
- 274806
sso:
    acs_url: https://customer1-dev.onelogin.com/trust/saml2/http-post/sso/932449
    certificate:
        id: 290729
        name: Standard Strength Certificate (2048-bit)
        value: '-----BEGIN CERTIFICATE-----

            MIID3zCCAsegAwIBAgIUM1r4RfduetLXV5xA+KTVtcfVUyAwDQYJKoZIhvcNAQEF

            BQAwRjERMA8GA1UECgwIQ3VzdG9tZXIxFTATBgNVBAsMDE9uZUxvZ2luIElkUDEa

            MBgGA1UEAwwRT25lTG9naW4gQWNjb3VudCAwHhcNMTkwNTEyMjI1ODM4WhcNMjQw

            NTEyMjI1ODM4WjBGMREwDwYDVQQKDAhDdXN0b21lcjEVMBMGA1UECwwMT25lTG9n

            aW4gSWRQMRowGAYDVQQDDBFPbmVMb2dpbiBBY2NvdW50IDCCASIwDQYJKoZIhvcN

            AQEBBQADggEPADCCAQoCggEBAOdh2ZInK/X0pxP3MwPlUPHe2AW+PGGe5pVlFbKM

            Ti8J6XbxLxRyG3ZHGecr90XL1DtCEMo6u+mgIslHnY/7TLrdSlOqehZtMlbdPuHi

            xv7EJw9VzXX91zCNIRR4dYISPEBia2VhZ4CYzJ78QY47kT/3Z9v+tYGBzgBk31Sw

            /FKidqdaUPfmSvG6Nzg1xNIz1X3XNJi7fEuiQcQFxFxMNUV9qV2uach6QxjhzJxB

            ClAOXARNLocc2zzYkqP9LYFkliwHjNx2JyTVBZljmMgi6a6eeexNqpniYDrKSct3

            6hSe8hWIzY8Rw3lQU3MHdo6nFwZvLSD+o1kFp+OxBnIOi+MCAwEAAaOBxDCBwTAM

            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRtKAoWtmzbiefFLFGauKe/tXE+wzCBgQYD

            VR0jBHoweIAUbSgKFrZs24nnxSxRmrinv7VxPsOhSqRIMEYxETAPBgNVBAoMCEN1

            c3RvbWVyMRUwEwYDVQQLDAxPbmVMb2dpbiBJZFAxGjAYBgNVBAMMEU9uZUxvZ2lu

            IEFjY291bnQgghQzWvhF92560tdXnED4pNW1x9VTIDAOBgNVHQ8BAf8EBAMCB4Aw

            DQYJKoZIhvcNAQEFBQADggEBAFswVjxnkxDr5d23pcneXGtf4jHvIY2kCQY/SKb0

            FpLXTIrTCAYqd/mflwWTdukYEVYT9jsNo5F+iqKMYeB0dgJpO4+j3aIvfp4DzILO

            3GZB/kbyMrLbo0DDd6LgjLCZj7P8H7cw5CUum/QZ1vI+BFxW8IVvVeEL7aY8awGT

            LhmZlOVgxSfLsv3DV27onOwleLbN6GgfL3B0kceV+udYQi6N6Q4G4JYWdSvz1Emj

            6z5PZz2sSfCtSxwzVkx+7XDxCUYiyr8HNZH+eK29eWB8/axh0/aOFrKpOsNu7iRB

            gE86YFCq0Qns6XFzapMl6wTf6p808yUCSvT/60YFq5WKjN0=

            -----END CERTIFICATE-----

            '
    issuer: https://app.onelogin.com/saml/metadata/4cc4f638-2888-47a6-a2d2-9893822d72da
    metadata_url: https://app.onelogin.com/saml/metadata/4cc4f638-2888-47a6-a2d2-9893822d72da
    sls_url: https://customer1-dev.onelogin.com/trust/saml2/http-redirect/slo/932449
tab_id: 292352
updated_at: '2019-07-30T00:46:23Z'
visible: true
